from gym_microrts.envs.global_agent_env import GlobalAgentEnv, GlobalAgentMiningEnv, GlobalAgentBinaryEnv, GlobalAgentAttackEnv, GlobalAgentProduceWorkerEnv
from gym_microrts.envs.local_agent_env import LocalAgentEnv
from gym_microrts.envs.global_agent_mining_hilbert_env import GlobalAgentMiningHilbertEnv